spring:
  application:
    name: meerCatDemo
# DBMS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/meerCatDemo
    username: postgres
    password: 1114
# security
  security:
    user:
      name: user
      password: 1234

# JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      # ??? ??? ??
      location: src/main/resources/static/upload
# logback
logging:
  level:
    root: info
    '[com.kws.meercat]': debug